// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwwGeBy9-bvq_SRt5ThBPZDzlPtrOvxco',
    appId: '1:1064440809316:web:1093ad8bac1c374ac99c71',
    messagingSenderId: '1064440809316',
    projectId: 'permaculture-app-18acc',
    authDomain: 'permaculture-app-18acc.firebaseapp.com',
    storageBucket: 'permaculture-app-18acc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMnZu7t7S0KvUWPDUMBuStaSKiMu9pzG0',
    appId: '1:1064440809316:android:43376c52fcb4f0b0c99c71',
    messagingSenderId: '1064440809316',
    projectId: 'permaculture-app-18acc',
    storageBucket: 'permaculture-app-18acc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKNmVonT4lgThMjyxnvKasHgRE2w8klvY',
    appId: '1:1064440809316:ios:51b23114f65ab59ec99c71',
    messagingSenderId: '1064440809316',
    projectId: 'permaculture-app-18acc',
    storageBucket: 'permaculture-app-18acc.firebasestorage.app',
    iosBundleId: 'com.example.permacultureApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKNmVonT4lgThMjyxnvKasHgRE2w8klvY',
    appId: '1:1064440809316:ios:51b23114f65ab59ec99c71',
    messagingSenderId: '1064440809316',
    projectId: 'permaculture-app-18acc',
    storageBucket: 'permaculture-app-18acc.firebasestorage.app',
    iosBundleId: 'com.example.permacultureApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwwGeBy9-bvq_SRt5ThBPZDzlPtrOvxco',
    appId: '1:1064440809316:web:09f9c259e62f8849c99c71',
    messagingSenderId: '1064440809316',
    projectId: 'permaculture-app-18acc',
    authDomain: 'permaculture-app-18acc.firebaseapp.com',
    storageBucket: 'permaculture-app-18acc.firebasestorage.app',
  );
}
